//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorioCINAPFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        public int ID_Alumno { get; set; }
        public Nullable<int> ID_Persona { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Matricula { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
