//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorioCINAPFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrera
    {
        public Carrera()
        {
            this.Grupoes = new HashSet<Grupo>();
        }
    
        public int ID_Carrera { get; set; }
        public string Nombre { get; set; }
        public string Abreviacion { get; set; }
    
        public virtual ICollection<Grupo> Grupoes { get; set; }
    }
}
