//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorioCINAPFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleGrupo
    {
        public int ID_DetalleGrupo { get; set; }
        public int ID_Persona { get; set; }
        public int ID_Grupo { get; set; }
    
        public virtual Grupo Grupo { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
