//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorioCINAPFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupo
    {
        public Grupo()
        {
            this.DetalleGrupoes = new HashSet<DetalleGrupo>();
            this.RegistroPrestamoLaboratorios = new HashSet<RegistroPrestamoLaboratorio>();
            this.RegistroPrestamoMaterials = new HashSet<RegistroPrestamoMaterial>();
            this.ReporteItems = new HashSet<ReporteItem>();
        }
    
        public int ID_Grupo { get; set; }
        public Nullable<int> Semestre { get; set; }
        public string Materia { get; set; }
        public int ID_Carrera { get; set; }
    
        public virtual Carrera Carrera { get; set; }
        public virtual ICollection<DetalleGrupo> DetalleGrupoes { get; set; }
        public virtual ICollection<RegistroPrestamoLaboratorio> RegistroPrestamoLaboratorios { get; set; }
        public virtual ICollection<RegistroPrestamoMaterial> RegistroPrestamoMaterials { get; set; }
        public virtual ICollection<ReporteItem> ReporteItems { get; set; }
    }
}
