//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorioCINAPFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laboratorio
    {
        public Laboratorio()
        {
            this.RegistroPrestamoLaboratorios = new HashSet<RegistroPrestamoLaboratorio>();
        }
    
        public int ID_Laboratorio { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual ICollection<RegistroPrestamoLaboratorio> RegistroPrestamoLaboratorios { get; set; }
    }
}
