//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorioCINAPFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maestro
    {
        public Maestro()
        {
            this.RegistroPrestamoLaboratorios = new HashSet<RegistroPrestamoLaboratorio>();
        }
    
        public int ID_Maestro { get; set; }
        public int ID_Persona { get; set; }
        public string Nombre { get; set; }
        public string Correo { get; set; }
        public string ClaveEmpleado { get; set; }
    
        public virtual ICollection<RegistroPrestamoLaboratorio> RegistroPrestamoLaboratorios { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
