//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorioCINAPFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.RegistroPrestamoMaterials = new HashSet<RegistroPrestamoMaterial>();
        }
    
        public int ID_Material { get; set; }
        public string CodigoSerie { get; set; }
        public Nullable<bool> Disponibilidad { get; set; }
        public int ID_TipoMaterial { get; set; }
        public Nullable<bool> EstadoFuncional { get; set; }
        public string EstadoDescripcion { get; set; }
        public bool Activo { get; set; }
    
        public virtual ICollection<RegistroPrestamoMaterial> RegistroPrestamoMaterials { get; set; }
        public virtual TipoMaterial TipoMaterial { get; set; }
    }
}
