//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorioCINAPFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroPrestamoMaterial
    {
        public int ID_RegistroPrestamoMaterial { get; set; }
        public int ID_Material { get; set; }
        public int ID_Persona { get; set; }
        public int ID_Grupo { get; set; }
        public bool Estado { get; set; }
        public string EstadoDescripcionEntrega { get; set; }
        public string EstadoDescripcionRecibido { get; set; }
        public bool EstadoFuncionalEntrega { get; set; }
        public Nullable<bool> EstadoFuncionalRecibido { get; set; }
        public System.DateTime FechaPrestamo { get; set; }
        public Nullable<System.DateTime> FechaRegreso { get; set; }
    
        public virtual Grupo Grupo { get; set; }
        public virtual Material Material { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
