//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorioCINAPFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroPrestamoLaboratorio
    {
        public int ID_RegistroPrestamoLaboratorio { get; set; }
        public int ID_Laboratorio { get; set; }
        public int ID_Maestro { get; set; }
        public int ID_Grupo { get; set; }
        public System.DateTime FechaEntrada { get; set; }
        public System.DateTime FechaSalida { get; set; }
        public bool Asistencia { get; set; }
    
        public virtual Grupo Grupo { get; set; }
        public virtual Laboratorio Laboratorio { get; set; }
        public virtual Maestro Maestro { get; set; }
    }
}
