//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorioCINAPFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelacionPersonaGrupo
    {
        public string Nombre { get; set; }
        public int ID_Persona { get; set; }
        public string TipoPersona { get; set; }
        public int ID_TipoPersona { get; set; }
        public string Materia { get; set; }
        public int ID_Grupo { get; set; }
    }
}
