//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorioCINAPFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoUsuario
    {
        public TipoUsuario()
        {
            this.Usuarios = new HashSet<Usuario>();
        }
    
        public int ID_TipoUsuario { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public bool Activo { get; set; }
    
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}
