//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorioCINAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        public int ID_Alumno { get; set; }
        public Nullable<int> ID_Persona { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Matricula { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
