//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorioCINAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.RegistroPrestamoMaterial = new HashSet<RegistroPrestamoMaterial>();
        }
    
        public int ID_Material { get; set; }
        public string CodigoSerie { get; set; }
        public Nullable<bool> Disponibilidad { get; set; }
        public int ID_TipoMaterial { get; set; }
        public Nullable<bool> EstadoFuncional { get; set; }
        public string EstadoDescripcion { get; set; }
        public bool Activo { get; set; }
    
        public virtual ICollection<RegistroPrestamoMaterial> RegistroPrestamoMaterial { get; set; }
        public virtual TipoMaterial TipoMaterial { get; set; }
    }
}
