//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorioCINAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public Persona()
        {
            this.Alumno = new HashSet<Alumno>();
            this.DetalleGrupo = new HashSet<DetalleGrupo>();
            this.Maestro = new HashSet<Maestro>();
            this.RegistroPrestamoMaterial = new HashSet<RegistroPrestamoMaterial>();
        }
    
        public int ID_Persona { get; set; }
        public int ID_TipoPersona { get; set; }
        public bool Activo { get; set; }
    
        public virtual ICollection<Alumno> Alumno { get; set; }
        public virtual ICollection<DetalleGrupo> DetalleGrupo { get; set; }
        public virtual ICollection<Maestro> Maestro { get; set; }
        public virtual TipoPersona TipoPersona { get; set; }
        public virtual ICollection<RegistroPrestamoMaterial> RegistroPrestamoMaterial { get; set; }
    }
}
