//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorioCINAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroPrestamoLaboratorio
    {
        public int ID_RegistroPrestamoLaboratorio { get; set; }
        public int ID_Laboratorio { get; set; }
        public int ID_Maestro { get; set; }
        public int ID_Grupo { get; set; }
        public System.DateTime FechaEntrada { get; set; }
        public System.DateTime FechaSalida { get; set; }
        public bool Asistencia { get; set; }
    
        public virtual Grupo Grupo { get; set; }
        public virtual Laboratorio Laboratorio { get; set; }
        public virtual Maestro Maestro { get; set; }
    }
}
