//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorioCINAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reporte
    {
        public Reporte()
        {
            this.ReporteItem = new HashSet<ReporteItem>();
        }
    
        public int ID_Reporte { get; set; }
        public int FechaInicioPeriodo { get; set; }
        public int FechaTerminacionPeriodo { get; set; }
    
        public virtual ICollection<ReporteItem> ReporteItem { get; set; }
    }
}
